version: 2.1
jobs:
    build:
        docker:
            - image: cimg/ruby
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        docker:
            - image: cimg/ruby
        steps:
            - checkout
            # 使用するsshの秘密鍵を指定する
            - add_ssh_keys:
                fingerprints:
                    - "75:e2:6c:f0:11:71:65:00:81:00:43:ba:76:6a:fe:44"
            # known_hosts に接続先(AWS)のホストを追加する
            - run: ssh-keyscan -p 22 ${HOST_NAME} >> ~/.ssh/known_hosts
            # ssh接続して作業を行う
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd webapp/docker/rails/src/goal-achievement && touch test.txt'
workflows:
    version: 2.1
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master


