version: 2.1
jobs:
    build:
        docker:
            - image: cimg/node:lts
        steps:
            - checkout
            - run: echo "Hello, World"
workflows:
    version: 2.1
    build_and_deploy:
        jobs:
            - build:

