version: 2.1
orbs:
    slack: circleci/slack@4.4.4
jobs:
    build:
        docker:
            - image: cimg/node:lts
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        docker:
            - image: cimg/node:lts
        steps:
            - checkout
            # 使用するsshの秘密鍵を指定する
            - add_ssh_keys:
                fingerprints:
                    - "75:e2:6c:f0:11:71:65:00:81:00:43:ba:76:6a:fe:44"
            # known_hosts に接続先(AWS)のホストを追加する
            - run: ssh-keyscan -p 22 ${HOST_NAME} >> ~/.ssh/known_hosts
            # ssh接続してスクリプトファイルを実行する
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd webapp/command && sh deploy.sh'
            # slack連携の設定
            - slack/notify: # 失敗時の通知
                channel: C02AHKSE2K1
                event: fail
                template: basic_fail_1
            - slack/notify: # 成功時の通知
                channel: C02AHKSE2K1
                event: pass
                template: basic_success_1
workflows:
    version: 2.1
    build_and_deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only: master-production
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master-production
                context: # ContextにSLACKという名前で追加した環境変数の設定を使用する
                    - SLACK


