version: 2.1
orbs:
    slack: circleci/slack@4.4.4
jobs:
    build:
        docker:
            - image: cimg/node:lts
        steps:
            - checkout
            - run: echo "Hello, World"
            - run: expr 1 / 0
            - slack/notify:
                channel: C02AHKSE2K1
                event: fail
                template: basic_fail_1
workflows:
    version: 2.1
    build_and_deploy:
        jobs:
            - build:
                context:
                    - SLACK

